### ISSUE TITLE
注册了试试，似乎无法注册？

### ISSUE THREAD

**Issue by jie-neng** [stevenwsg/XSYBBS#1]
注册说邮箱格式不对

**Comment by stevenwsg** [comment]
现在好了嘛？
可以先用用我的账号： 账号：wsg, 密码：123
这个问题我有空看看

**Comment by stevenwsg** [comment]
> 注册说邮箱格式不对

现在好了嘛？
可以先用用我的账号： 账号：wsg, 密码：123
这个问题我有空看看

**Comment by stevenwsg** [comment]
这个是服务器的校验， 你注册时邮箱格式正确嘛？ 后面以@xxx.com结尾。 随便输个kkkx.@134.com都可以通过的。除非你输得太简单了，可能和后台的用户注册邮箱重复了

**Comment by stevenwsg** [comment]
> 注册说邮箱格式不对
这个是服务器的校验， 你注册时邮箱格式正确嘛？ 后面以@xxx.com结尾。 随便输个kkkx.@134.com都可以通过的。除非你输得太简单了，可能和后台的用户注册邮箱重复了

**Comment by stevenwsg** [comment]
> 注册说邮箱格式不对


这个是服务器的校验， 你注册时邮箱格式正确嘛？ 后面以@xxx.com结尾。 随便输个kkkx.@134.com都可以通过的。除非你输得太简单了，可能和后台的用户注册邮箱重复了
