### ISSUE TITLE
弄倒Android Studio里，构建的gradle有问题

### ISSUE THREAD

**Issue by jie-neng** [stevenwsg/XSYBBS#2]
![S{1@UDCMY{TM`@FZ}G(L{S1](https://user-images.githubusercontent.com/58629010/119266956-6e91f780-bc1f-11eb-9cff-0137864f3134.png)

**Comment by stevenwsg** [comment]
你有配置Flutter的环境嘛？
先配置一下Flutter的环境，编译一下Flutter工程，在编译原生工程
可以参考这个： https://juejin.cn/post/6946172602310213645

**Comment by stevenwsg** [comment]
你有配置Flutter的环境嘛？
先配置一下Flutter的环境，编译一下Flutter工程，在编译原生工程
可以参考这个： https://juejin.cn/post/6946172602310213645
