### ISSUE TITLE
项目导入问题

### ISSUE THREAD

**Issue by 13209643545** [stevenwsg/XSYBBS#5]
新的项目导入后怎么运行呢？直接import project会提示setinggradle错误 然后就不能继续下去了 先运行flutter后运行这个 到导入maven-metadata

**Comment by stevenwsg** [comment]
> 新的项目导入后怎么运行呢？直接import project会提示setinggradle错误 然后就不能继续下去了 先运行flutter后运行这个 到导入maven-metadata

先运行Flutter项目在运行原生工程吧。 flutter项目里面有个原生的Android项目。这个是gitIngore的，并没有推送上去。 需要你自己编译flutter工程自动生成出来

**Comment by 13209643545** [comment]
懂了 下载的工程文件有两个，一个是flutter_bbs，一个是android项目，先运行flutter，然后再运行这个android项目，我这样试过了，最后生成的app个人中心会崩溃 mg13209643545 ***@***.*** 签名由 网易邮箱大师 定制 在2021年06月06日 13:32，wsg 写道： 新的项目导入后怎么运行呢？直接import project会提示setinggradle错误 然后就不能继续下去了 先运行flutter后运行这个 到导入maven-metadata 先运行Flutter项目在运行原生工程吧。 flutter项目里面有个原生的Android项目。这个是gitIngore的，并没有推送上去。 需要你自己编译flutter工程自动生成出来 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by stevenwsg** [comment]
> 懂了 下载的工程文件有两个，一个是flutter_bbs，一个是android项目，先运行flutter，然后再运行这个android项目，我这样试过了，最后生成的app个人中心会崩溃 mg13209643545 ***@***.*** 签名由 网易邮箱大师 定制 在2021年06月06日 13:32，wsg 写道： 新的项目导入后怎么运行呢？直接import project会提示setinggradle错误 然后就不能继续下去了 先运行flutter后运行这个 到导入maven-metadata 先运行Flutter项目在运行原生工程吧。 flutter项目里面有个原生的Android项目。这个是gitIngore的，并没有推送上去。 需要你自己编译flutter工程自动生成出来 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

<img width="833" alt="A432D68ECA9505DF632028DE94C4B2A3" src="https://user-images.githubusercontent.com/22788925/120914221-31be0a00-c6cf-11eb-8e40-47e142ee2c92.png">

这个是崩溃堆栈

![image](https://user-images.githubusercontent.com/22788925/120914240-4dc1ab80-c6cf-11eb-843b-4efc0e202c26.png)

这个是你的手机吧？

我刚才修复了， 你拉一下最新代码试试

修复的是这个提交，你可以看看 ：https://github.com/stevenwsg/XSYBBS/commit/f3cf4de32677242d367789a5c1ce426e96ff6b4b

感觉Bmob那边 有点问题，不知道问什么没有拿到用户信息

**Comment by 13209643545** [comment]
太感谢了！！🤙🤙🤙 mg13209643545 ***@***.*** 签名由 网易邮箱大师 定制 在2021年06月06日 14:00，wsg 写道： 懂了 下载的工程文件有两个，一个是flutter_bbs，一个是android项目，先运行flutter，然后再运行这个android项目，我这样试过了，最后生成的app个人中心会崩溃 mg13209643545 @.*** 签名由 网易邮箱大师 定制 在2021年06月06日 13:32，wsg 写道： 新的项目导入后怎么运行呢？直接import project会提示setinggradle错误 然后就不能继续下去了 先运行flutter后运行这个 到导入maven-metadata 先运行Flutter项目在运行原生工程吧。 flutter项目里面有个原生的Android项目。这个是gitIngore的，并没有推送上去。 需要你自己编译flutter工程自动生成出来 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 这个是崩溃堆栈 这个是你的手机吧？ 我刚才修复了， 你拉一下最新代码试试 修复的是这个提交，你可以看看 ：f3cf4de 感觉Bmob那边 有点问题，不知道问什么没有拿到用户信息 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
