### ISSUE TITLE
测试运行效果问题

### ISSUE THREAD

**Issue by 13209643545** [stevenwsg/XSYBBS#7]
测试效果：聊天发送视频点击无反应，点击拍照回崩溃，点击位置崩溃
查看报错，发现mainfest里有三处爆红，
<uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION"
        tools:ignore="MockLocation" />
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"
        tools:ignore="ProtectedPermissions"/>
已修改为忽略
<service
            android:name="com.baidu.location.f"  ------此处爆红
            android:enabled="true"
            android:process=":remote"
            tools:ignore="MissingClass">
        </service>
目前没找到解决方法。

**Comment by stevenwsg** [comment]
> 测试效果：聊天发送视频点击无反应，点击拍照回崩溃，点击位置崩溃
> 查看报错，发现mainfest里有三处爆红，
> 
> 
> 已修改为忽略
> <service
> android:name="com.baidu.location.f" ------此处爆红
> android:enabled="true"
> android:process=":remote"
> tools:ignore="MissingClass">
> 
> 目前没找到解决方法。

好的，我后面看看~

**Comment by stevenwsg** [comment]
> 测试效果：聊天发送视频点击无反应，点击拍照回崩溃，点击位置崩溃
> 查看报错，发现mainfest里有三处爆红，
> 
> 
> 已修改为忽略
> <service
> android:name="com.baidu.location.f" ------此处爆红
> android:enabled="true"
> android:process=":remote"
> tools:ignore="MissingClass">
> 
> 目前没找到解决方法。

我用网易 mumu模拟器尝试了一下，发现拍照是正常的。 点击位置会崩溃。
麻烦能提供下你点击拍照的崩溃日志嘛？ 我也去bugly上看看

**Comment by stevenwsg** [comment]
> 测试效果：聊天发送视频点击无反应，点击拍照回崩溃，点击位置崩溃
> 查看报错，发现mainfest里有三处爆红，
> 
> 
> 已修改为忽略
> <service
> android:name="com.baidu.location.f" ------此处爆红
> android:enabled="true"
> android:process=":remote"
> tools:ignore="MissingClass">
> 
> 目前没找到解决方法。

这两个问题， 目前都提给了环信的官方。 先等他们的回复吧

第一个：https://github.com/easemob/easeui/issues/214
第二个：https://github.com/easemob/easeui/issues/215

**Comment by stevenwsg** [comment]
环信这个sdk真的是垃圾， 定位的问题还在解决

**Comment by stevenwsg** [comment]
> 测试效果：聊天发送视频点击无反应，点击拍照回崩溃，点击位置崩溃
> 查看报错，发现mainfest里有三处爆红，
> 
> 
> 已修改为忽略
> <service
> android:name="com.baidu.location.f" ------此处爆红
> android:enabled="true"
> android:process=":remote"
> tools:ignore="MissingClass">
> 
> 目前没找到解决方法。

集成了百度地图4.0 的版本到主module， 地图定位的crash修复了。 16年的sdk了。 环信也没更新，真实服了
